name: Book Problem
description: Report a problem in the book
title: "please enter a brief summary here"
assignees:
  - shriram
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more information?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: which-part
    attributes:
      label: Which part are you commenting on?
      description: Please provide some way of locating the place in the book.
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What's the problem?
      description: Please report what the problem is.
    validations:
      required: true
